362/standardize logging
elementary-robotics/atom pull request #364
Opened 2020-09-07 03:55 UTC by MeganParadowski1

This PR Standardize logging to integrate with any log management service provider: 
1. mounts a shared volume to all docker containers at /var/log/atom
2. Utilizes a RotatingFileHandler logger to silently and automatically rotate the log file when it gets to a given size (currently 2000 bytes)
3. Removes the stdout log function and outputs logs with the element logger

2020-09-07 14:47 UTC, dpipemazo requested changes
Overall looks good. Please handle invalid log levels and please don't deprecate `element.log` but instead forward all calls to `element.log` through the new logging utility.

2020-09-07 14:47 UTC, dpipemazo commented on .circleci/docker-compose-circle.yml
> +      - log:/var/log/atom
Interesting syntax here as this isn't how we do it for the `/shared` -- this definitely uses the `tmpfs` and not a local folder named `log`?

2020-09-07 14:47 UTC, dpipemazo commented on languages/python/atom/element.py
> +        self.logger.setLevel(os.getenv("ATOM_LOG_LEVEL", "INFO"))
This is making a bit of an assumption that the user set a valid level. We should error-check on that and correct for them, i.e. if they set something invalid we fall back to "INFO". A fallback to a default level would be a better behavior than a crash/error due to the user setting something invalid.

2020-09-07 14:47 UTC, dpipemazo commented on languages/python/atom/element.py
> -    def log(self, level, msg, stdout=True, _pipe=None, redis=False):
Please keep this for legacy purposes. When users use this API you should translate the calls into the right `self.logger` calls. This will give us free upgrades and we can encourage people to stop using it in a future release.

2020-09-07 15:10 UTC, MeganParadowski1 commented on .circleci/docker-compose-circle.yml
> +      - log:/var/log/atom
Yes, tested on the container with 
`# stat --file-system --format=%T /var/log/atom
tmpfs`

2020-09-07 15:11 UTC, MeganParadowski1 commented on languages/python/atom/element.py
> +        self.logger.setLevel(os.getenv("ATOM_LOG_LEVEL", "INFO"))
Good point - will update!

2020-09-07 15:11 UTC, dpipemazo commented
@MeganParadowski1 Please also add parameterization for the log file size -- ideally through an env variable s.t. different elements can change their rotation size if they'd like.

2020-09-07 15:12 UTC, dpipemazo commented on languages/python/atom/element.py
> +        rfh = logging.handlers.RotatingFileHandler(f'{ATOM_LOG_DIR}{self.name}.log', maxBytes=2000)
Please make this `2000` a parameter, set by ENV

2020-09-07 15:13 UTC, dpipemazo commented on languages/python/atom/element.py
> +        rfh = logging.handlers.RotatingFileHandler(f'{ATOM_LOG_DIR}{self.name}.log', maxBytes=2000)
Please also perform some escaping (if necessary) on the element name to ensure it complies with the character rules for filenames. I believe the user could currently set an element name that would break this.

2020-09-07 17:23 UTC, dpipemazo commented on languages/python/atom/element.py
> +ATOM_LOG_FILE_SIZE = os.getenv("ATOM_LOG_FILE_SIZE", DEFAULT_LOG_FILE_SIZE)
I think you're going to need an `int` around this?

2020-09-07 17:24 UTC, dpipemazo commented on languages/python/atom/element.py
> +            numeric_level = 20
What does `20` mean here? Please avoid "magic" numbers where possible, either through thorough commenting or constants.

2020-09-07 17:29 UTC, MeganParadowski1 commented on languages/python/atom/element.py
> +            numeric_level = 20
It's the numeric log level for INFO - I'll update

2020-09-07 17:30 UTC, MeganParadowski1 commented on languages/python/atom/element.py
> +ATOM_LOG_FILE_SIZE = os.getenv("ATOM_LOG_FILE_SIZE", DEFAULT_LOG_FILE_SIZE)
You're right, I set it in the dockerfile as an int, but if the user sets it then it may be a string

2020-09-16 22:31 UTC, dpipemazo requested changes
Looking good.

Please tighten up the error-handling in the logging initialization but otherwise in great shape!

2020-09-16 22:31 UTC, dpipemazo commented on languages/python/atom/config.py
> +DEFAULT_LOG_FILE_SIZE = 2000
Slight semantic note -- I typically prefer to have constants start with their "module"/functionality to make it a bit easier to surface what it pertains to. Here, we could do `LOG_DEFAULT_FILE_SIZE` and `LOG_DEFAULT_LEVEL` to help group these under the logical `LOG` "module"/functionality. This applies throughout to functions, etc.

2020-09-16 22:31 UTC, dpipemazo commented on languages/python/atom/element.py
> +        except Exception as e:
Generic try/except is generally not a great strategy. We use it in certain places but I believe the better way to handle this is to catch the errors we know about/can reasonably happen explicitly and let it throw in the event we hit a new one.

One downside of this way of doing it is that you lose the full stack trace as well which is quite useful. 

Finally, putting this much code in a single `try/except` is also not ideal -- they should be small and specific to known errors in each case.

2020-09-16 22:31 UTC, dpipemazo commented on languages/python/atom/element.py
> +        Forwards calls to self.logger
:+1:

2020-09-23 16:43 UTC, merged