Convert syslog loglevel
elementary-robotics/atom pull request #384
Opened 2020-11-11 08:44 UTC by MeganParadowski1

- Convert syslog log level to python log level to support the deprecated element.log() method
- Retain loggers by element name to avoid duplicating across multiple instances of an element

2020-11-11 16:29 UTC, dpipemazo requested changes
I am not sure the global-dict logger check will do us much good as these aren't shared in multi-process environments. 

Are we adding/do we have code to clean up the logger in the element deletion stack? That can also fix the problem and I'm not sure I see it in here.

2020-11-11 16:29 UTC, dpipemazo commented on languages/python/atom/element.py
> +LOGGERS = {}
This strategy won't hold across processes I think

2020-11-11 16:29 UTC, dpipemazo commented on languages/python/atom/messages.py
> +LOG_LEVEL_CONVERSION = {
:+1: this is clever.

2020-11-12 20:18 UTC, MeganParadowski1 commented
> I am not sure the global-dict logger check will do us much good as these aren't shared in multi-process environments.
> 
> Are we adding/do we have code to clean up the logger in the element deletion stack? That can also fix the problem and I'm not sure I see it in here.

@dpipemazo I'm having a hard time determining where exactly the element is deleted. Could you point me in the right direction?

2020-11-12 21:56 UTC, dpipemazo commented
@MeganParadowski1 sure, in Python the __del__ method is called whenever the Python garbage collector/runtime deletes an element. 

https://github.com/elementary-robotics/atom/blob/latest/languages/python/atom/element.py#L429

This is where we put code that we want to run when an element is deleted.

2021-04-07 15:07 UTC, closed without merging