Add user-specified reference key
elementary-robotics/atom pull request #390
Opened 2020-12-10 02:12 UTC by aywaldron

Resolves #389 

Also updated docker-compose files to work with most recent atom version

2020-12-10 02:15 UTC, dpipemazo requested changes

2020-12-10 02:15 UTC, dpipemazo commented on languages/python/atom/element.py
> +        return f"reference:{self.name}:{key}"
I think as designed right now if we want data passed between elements it will only work if the caller of the API has an element with the same name? This is fairly limiting. I think if we made it `reference:{key}` it would allow us to have any element be able to pull/write to a piece of data by name which is going to give us slightly better functionality.

2020-12-10 02:15 UTC, dpipemazo commented on languages/python/atom/element.py
>                  # Now, we can go ahead and do the SET in redis for the key
Do we also need to modify the reference get API?

2020-12-10 02:29 UTC, aywaldron commented on languages/python/atom/element.py
>                  # Now, we can go ahead and do the SET in redis for the key
`reference_get` takes in the entire reference key so it does not need to be modified if its able to know the full key used by `reference_create`.

2020-12-11 18:36 UTC, dpipemazo commented on languages/python/atom/element.py
> +                if field != b"override":
might want to make this a list of "reserved" keys for future expansion

2020-12-11 19:07 UTC, aywaldron commented on languages/python/atom/element.py
> +                if field != b"override":
yes great idea

2020-12-12 01:36 UTC, dpipemazo requested changes
Overall this feature looks great and the API spec is pretty clever. I really like the **override** field applying on a per-key basis.

2020-12-12 01:36 UTC, dpipemazo commented on README.md
> +git submodule update --init --recursive
:+1: this is great, thanks!

2020-12-12 01:36 UTC, dpipemazo commented on doc/source/includes/sdk-specification.md
> +| `timeout_ms` | int | How long the parameter should exist in Atom. This sets the expiry timeout in redis. Units in milliseconds. Set to 0 for no timeout, i.e. parameter exists until explicitly delet
I think the default timeout on parameters should be infinite unlike references, what do you think? Regardless of choice might be nice to document the default here.

2020-12-12 01:36 UTC, dpipemazo commented on doc/source/includes/sdk-specification.md
> +Tuple of key parameter is stored at, and list of parameter fields written to.
Do we need to return and pass around the key? This is what we do on references, but I think that's because we use random strings in the reference keys.

If possible, it would be nice to have an API where we didn't need to track this key and could just `parameter_write("some_key")` and `parameter_delete("some_key")`

2020-12-12 01:36 UTC, dpipemazo commented on doc/source/includes/sdk-specification.md
> +raise an Exception. Otherwise, continue writing the parameter.
:+1:

2020-12-12 01:36 UTC, dpipemazo commented on languages/python/atom/config.py
> +RESERVED_PARAM_FIELDS = [OVERRIDE_PARAM_FIELD, SERIALIZATION_PARAM_FIELD]
:+1:

2020-12-12 01:36 UTC, dpipemazo commented on languages/python/atom/element.py
> +    def _make_reference_id(self, key=None):
were the changes here intentional?

2020-12-12 01:36 UTC, dpipemazo commented on languages/python/atom/element.py
> +        self, key, data, override=True, serialization=None, timeout_ms=10000
Let's set the default to infinite time on parameters -- I see them being used much less frequently than references and for things like system configurations which get written at boot and read for the uptime of the device.

2020-12-12 01:36 UTC, dpipemazo commented on languages/python/atom/element.py
> +            override (bool, optional): whether or not hash fields can be
this is subtle but a **really nice** design I think. As implemented, it seems that the override field will allow for adding **new** fields but not overwriting any existing ones?

2020-12-12 01:36 UTC, dpipemazo commented on languages/python/atom/element.py
> +                    _pipe.hget(key, OVERRIDE_PARAM_FIELD)
Maybe we should check for the override before checking the keys since it might overall save time? If the override is false we don't have to run all of the `hget`s on the keys

2020-12-12 01:36 UTC, dpipemazo commented on languages/python/atom/element.py
> +        return key, fields
I see we're returning the original key -- was there a particular reason to do this?

2020-12-12 01:36 UTC, dpipemazo commented on languages/python/atom/element.py
> +        self.reference_delete(f"parameter:{key}")
should we make a helper function to make this string of `parameter:{key}` to keep this DRY?

2020-12-12 01:36 UTC, dpipemazo commented on languages/python/atom/element.py
> +        self, *data, key=None, serialization=None, serialize=None, timeout_ms=10000
I think this might be an improvement, but it might have also slipped in?

2020-12-12 01:40 UTC, aywaldron commented on doc/source/includes/sdk-specification.md
> +| `timeout_ms` | int | How long the parameter should exist in Atom. This sets the expiry timeout in redis. Units in milliseconds. Set to 0 for no timeout, i.e. parameter exists until explicitly delet
Yeah I was thinking about that too -- if so, would we need to make the element that writes them responsible for deleting them on shutdown? Or do you not see there being any issue with them never being removed explicitly?

2020-12-12 01:41 UTC, aywaldron commented on doc/source/includes/sdk-specification.md
> +Tuple of key parameter is stored at, and list of parameter fields written to.
We don't have to! As written, the API already works like you described. I can remove the key return without having to make any other changes.

2020-12-12 01:42 UTC, aywaldron commented on languages/python/atom/element.py
> +    def _make_reference_id(self, key=None):
I just left in the work I previously did on this ticket which allows users to specify their own reference key since I thought we wanted that enhancement as well. I can remove if we don't need this now that we have parameters?

2020-12-12 01:42 UTC, aywaldron commented on languages/python/atom/element.py
> +        self, key, data, override=True, serialization=None, timeout_ms=10000
Sounds good :+1: do we need an explicit removal policy to be documented or just let them sit around?

2020-12-12 01:45 UTC, aywaldron commented on languages/python/atom/element.py
> +            override (bool, optional): whether or not hash fields can be
Correct, if override is false you cannot overwrite existing fields, but you could add brand new ones.

2020-12-12 01:48 UTC, aywaldron commented on languages/python/atom/element.py
> +                    _pipe.hget(key, OVERRIDE_PARAM_FIELD)
Sure that works. As written, we save time on checking override if no requested keys already exist, but you're right that we'll save more time on average by checking override first since there will be >1 requested key on average.

2020-12-12 01:48 UTC, aywaldron commented on languages/python/atom/element.py
> +        return key, fields
I'll remove this :)

2020-12-12 01:49 UTC, dpipemazo commented on doc/source/includes/sdk-specification.md
> +| `timeout_ms` | int | How long the parameter should exist in Atom. This sets the expiry timeout in redis. Units in milliseconds. Set to 0 for no timeout, i.e. parameter exists until explicitly delet
I imagine the total amount of data here will be negligible and we can document that the creator should clean them up. If we wanted to we could log all parameters created in a dict on the element itself subtly and then clean them up in the destructor, but this might be overkill.

2020-12-12 01:49 UTC, aywaldron commented on languages/python/atom/element.py
> +        self, *data, key=None, serialization=None, serialize=None, timeout_ms=10000
This is the previous version of the work I did on adding user-specified keys to references. Can remove if we don't want this anymore.

2020-12-12 01:49 UTC, dpipemazo commented on doc/source/includes/sdk-specification.md
> +Tuple of key parameter is stored at, and list of parameter fields written to.
Yeah, I think it might be a bit confusing for those familiar with the reference API?

2020-12-12 01:50 UTC, dpipemazo commented on languages/python/atom/element.py
> +    def _make_reference_id(self, key=None):
ah, that's great. Did we update the reference docs for this?

2020-12-12 01:50 UTC, dpipemazo commented on languages/python/atom/element.py
> +    def _make_reference_id(self, key=None):
Definitely still a nice enhancement.

2020-12-12 01:52 UTC, aywaldron commented on doc/source/includes/sdk-specification.md
> +| `timeout_ms` | int | How long the parameter should exist in Atom. This sets the expiry timeout in redis. Units in milliseconds. Set to 0 for no timeout, i.e. parameter exists until explicitly delet
Agree, would be a good safeguard but likely overkill as long as `parameter_write` is not misused by any elements. Is redis cleared when we restart nucleus/restart a stack?

2020-12-12 01:53 UTC, aywaldron commented on languages/python/atom/element.py
> +    def _make_reference_id(self, key=None):
Oh good reminder, I didn't update the reference docs -- will add that.

2020-12-12 03:26 UTC, dpipemazo commented on doc/source/includes/sdk-specification.md
> +| `timeout_ms` | int | How long the parameter should exist in Atom. This sets the expiry timeout in redis. Units in milliseconds. Set to 0 for no timeout, i.e. parameter exists until explicitly delet
redis is cleared on nucleus restart :+1:

2020-12-12 03:27 UTC, dpipemazo commented on languages/python/atom/element.py
> +        self, key, data, override=True, serialization=None, timeout_ms=10000
I think we should maybe just document that they'll live forever by default and the user should be careful to clean them up.

2020-12-12 03:29 UTC, dpipemazo commented on languages/python/atom/element.py
> +                    _pipe.hget(key, OVERRIDE_PARAM_FIELD)
Yeah, I think it's not clear exactly which use case will be more common but I think the fail case is worse for large numbers of keys and no override than a single extra call. I do tend to agree more keys is likely to be more common as well.

2020-12-15 00:20 UTC, aywaldron commented
Thanks for the feedback @dpipemazo - I have pushed the following changes:
- Updated default parameter timeout to be 0 (no timeout)
- Moved override check before requested fields check when parameter already exists
- Added check for matching serialization method when attempting to update parameter (decided not to support switching serialization method after initial parameter write)
- Updated reference API to allow for multiple user-specified keys (previously only worked when creating one reference at a time)
- Updated reference documentation with new user-specified key capability

2020-12-16 02:07 UTC, dpipemazo approved these changes
Overall looks great. It's nice that DEL and PEXPIRE work on both keys and hashes to share that logic under the hood.

2020-12-16 02:07 UTC, dpipemazo commented on languages/python/atom/element.py
> +                    raise AtomError(
:+1: nice!

2020-12-16 02:07 UTC, dpipemazo commented on languages/python/atom/element.py
> +        self.reference_update_timeout_ms(self._make_parameter_key(key), timeout_ms)
Similar to `DEL`, does `PEXPIRE` also work on hashes? That's nice.

2020-12-16 04:33 UTC, aywaldron commented on languages/python/atom/element.py
> +        self.reference_update_timeout_ms(self._make_parameter_key(key), timeout_ms)
Yes, so it actually works on Redis keys, and it doesn't matter what data type is stored in the key.

2020-12-18 17:55 UTC, merged