Remove lazycontract (not used)
elementary-robotics/atom pull request #406
Opened 2021-02-18 13:42 UTC by kylebebak

Closes #405

2021-03-01 16:08 UTC, dpipemazo approved these changes
:+1: looks good. Just re-running the failed build job to see if it was a fluke (should be, not sure what could have broken just that one build)

2021-03-01 16:27 UTC, dpipemazo requested changes
@kylebebak build failure doesn't seem to be a fluke; not sure why it's picking up python2 as the default in that base image but we need to look into it.

2021-03-01 16:27 UTC, dpipemazo commented on languages/python/setup.py
> +    install_requires=["msgpack==0.6.2"],
Don't we also need redis-py, redistimeseries-py, etc?

2021-03-01 17:27 UTC, kylebebak commented on languages/python/setup.py
> +    install_requires=["msgpack==0.6.2"],
You're right -- I didn't see these in `requirements.txt`, but see they're in `Dockerfile-base` and `Dockerfile`.

2021-03-01 17:37 UTC, kylebebak commented
Might be related to `setup.py`, `install_requires=["msgpack==0.6.2"]`. I'll have a look

2021-03-01 18:06 UTC, dpipemazo commented on languages/python/setup.py
> +    install_requires=["msgpack==0.6.2"],
I think we also need numpy, arrow, etc. Overall it seems like we're working on multiple features here and I'd recommend scoping this down to removing `lazycontract` and then getting a separate issue to get us on Pip. Grouping multiple things into one PR is likely not the best idea.

2021-03-01 19:50 UTC, kylebebak commented on languages/python/setup.py
> +    install_requires=["msgpack==0.6.2"],
@dpipemazo 

Agreed, I thought this would be simple and quick, and it wasn't, but even if it were putting these both into the same PR isn't a good idea.

I've scoped it down to just removing `lazycontract`

2021-03-04 00:43 UTC, dpipemazo commented
@kylebebak turns out it was in Redis Time Series: https://github.com/RedisTimeSeries/RedisTimeSeries/issues/660

I'm fixing it in the PR to bring all of our builds up to Python3.7, and then we can rebase this atop that.

2021-03-08 15:09 UTC, dpipemazo requested changes
@kylebebak I think it's still in the `requirements.txt`

2021-03-08 18:05 UTC, dpipemazo approved these changes

2021-03-08 18:22 UTC, merged