Add type hints to atom python
elementary-robotics/atom pull request #408
Opened 2021-02-24 19:59 UTC by slaigai

Closes #407

2021-03-04 19:57 UTC, dpipemazo commented
@slaigai may be a bit of a naive question but how do we know that the type hints added are correct? Are we running `pyright` or similar on the test cases in CI to ensure/enforce/validate the type hinting in the APIs?

2021-03-04 20:15 UTC, slaigai commented
> @slaigai may be a bit of a naive question but how do we know that the type hints added are correct? Are we running `pyright` or similar on the test cases in CI to ensure/enforce/validate the type hinting in the APIs?

Oh, right. Not a naive question at all. We still need to figure out how we're going to set up the type checker per #413 . Meanwhile, I will expand the scope of this PR to include the following:
- add type hints
- add type checker to atom repo CI baked into test container. follow up with transition after #413  to replace this type checker
- fix type errors raised by type checker

2021-03-07 15:00 UTC, kylebebak commented on Dockerfile
> +# Install pyright
Cool, same recipe for adding type checking to test container in VP

2021-03-07 15:04 UTC, kylebebak commented on languages/python/atom/messages.py
> +@overload
Nice use of overload. It also makes it more obvious that this function signature is a little weird, which is a nice benefit of adding type hints!

2021-03-07 15:07 UTC, kylebebak commented on languages/python/atom/messages.py
> +        serialize: Optional[bool] = None,
Tracing the code back to the `serialization.py` module, I'm pretty sure `serialization` here, and probably everywhere else, must be one of `"msgpack", "arrow", "none"`

Let's use `Literal`!

2021-03-07 15:09 UTC, kylebebak commented on languages/python/atom/serialization.py
> +def serialize(data, method: Optional[str] = "none"):
Let's also use `Literal` and make this one of `"msgpack", "arrow", "none"`

2021-03-07 15:09 UTC, kylebebak commented on languages/python/atom/serialization.py
> +def deserialize(data, method: Optional[str] = "msgpack"):
Ditto

2021-03-07 15:31 UTC, kylebebak commented on languages/python/atom/element.py
> +        self.handler_map: dict[str, Any] = {}
Can't be sure this is always true, but it looks like the values in `self.handler_map` have the following shape

```py
        self.handler_map[HEALTHCHECK_COMMAND] = {
            "handler": handler,
            "serialization": None,
        }
```

We should use [TypedDict](https://www.python.org/dev/peps/pep-0589/) here. Something like:

```
class Handler(TypedDict):
    handler: Callable
    serialization: Optional[Literal[...]]
```

Then we'd have `self.handler_map: dict[str, Handler]`

2021-03-07 15:38 UTC, kylebebak commented on languages/python/atom/element.py
> +        stream_handlers: Sequence[StreamHandler],
Awesome =)

Also, I had a look at `StreamHandler`, and noticed that it has some validation code:

```
        if not isinstance(element, str):
            raise TypeError("element must be a str")
        if not isinstance(stream, str):
            raise TypeError("stream must be a str")
        if not callable(handler):
            raise TypeError("handler must be a function")
```

Given that the signature has type hints, and we're enabling type checking in this repo, I think this code, and code like this, is probably redundant an undesirable (I gave a bit of similar feedback in the VP types PR)

2021-03-07 15:45 UTC, kylebebak commented on languages/python/atom/element.py
> +        field_data_map: dict,
Can this be any more explicit, e.g. `dict[str, Any]`?

2021-03-07 15:48 UTC, kylebebak commented on languages/python/atom/element.py
> +            raise TypeError(
Very nice =)

This is a good example fo where raising this type error is necessary, even though **within this repo** the type checker would protect us from passing in an invalid type.

Methods exposed on `Element`, such as `reference_create`, are used and will be used in edge repos without type checking, which means we can't assume client code in other repos won't pass in invalid types for arguments like `keys`

2021-03-07 15:50 UTC, kylebebak requested changes
Looks great! Just some general feedback and a few suggestions :

- remove validation code if it's unnecessary (e.g. in `Acknowledge`, `Log`, `StreamHandler`) in `messages.py`
  + all this validation would be unnecessary if we were using `pyright` in other repos that use these classes; it's __unnecessary now__ if other repos don't use these classes, and they're only used internally; for example, the type checker simply won't allow us to pass in an `int` for an `element` argument of type `str`
- tighten up types where possible in containers (especially dicts)
- use `TypedDict` where appropriate
- use literal where appropriate, e.g. wherever we have a `serialization` argument

@slaigai Also, I think we should add documentation to README on how to run type checking in this repo, similar to what you did in VP.

-----

And one other thing that should probably be a separate issue, and that dovetails with publishing atom on PyPI. I created this issue here:

2021-03-08 19:37 UTC, slaigai commented
> use literal where appropriate, e.g. wherever we have a `serialization` argument

@kylebebak good suggestion. I've created a type alias in `serialization.py` that's reused across atom. We can import type aliases just like any other object from the `serialization` module. As you might have already figured out, this encourages code reuse and makes sure that there is exactly one place to edit when modifying the list of valid serialization methods.

2021-03-08 21:49 UTC, slaigai commented on languages/python/atom/element.py
> +        stream_handlers: Sequence[StreamHandler],
Thanks for calling this out, you gave useful insights here about redundant validation code! While I would agree with removing type validations for private functions, I have concerns about removing type checks for the public API (primarily those in messages.py). These may be imported into contexts where type checking is not performed as you mentioned in your review comment.

> if we think a class might be used by other repos, having this validation code might be useful, because we don't know if those repos are using pyright; most of them aren't

From a risk/benefit perspective, I think we'd incur more risk (e.g. hard-to-trace bugs, unusual error modes from incorrect usage) by removing these checks than any performance or maintainability gains. What do you think @kylebebak ?

2021-03-08 23:12 UTC, kylebebak commented on languages/python/atom/element.py
> +class HandlerDict(TypedDict, total=False):
Nice use of `total=False` here so that deserialize isn't a required key (which is different from being `Optional`)

2021-03-08 23:13 UTC, kylebebak commented on languages/python/atom/element.py
> +DuplicatePolicy = Literal["block", "first", "last", "min", "max"]
String literal union types =)

2021-03-08 23:14 UTC, kylebebak commented on languages/python/atom/serialization.py
> +SerializationMethod = Literal["msgpack", "arrow", "none"]
This is used in like 20 places, this is excellent

2021-03-08 23:17 UTC, kylebebak commented on languages/python/atom/element.py
> +        stream_handlers: Sequence[StreamHandler],
I think you're right. We talked about this a bit, and concluded that code in Atom should be written defensively, because repos that depend on atom might call code in this repo, and they might not be using a checker

Code in other repos, like vision processing, should not have defensive "validation" code if they have type hints

2021-03-08 23:18 UTC, kylebebak approved these changes
LGTM, this is ready to go!

2021-03-08 23:43 UTC, merged