Adds a method to list parameters
elementary-robotics/atom pull request #476
Opened 2021-06-03 21:44 UTC by sgord512

This is just a thin wrapper around `Element._redis_scan_keys` returning all parameter keys matching a given pattern.

Closes #450

2021-06-04 00:02 UTC, slaigai requested changes
Nice first pass! I have some requested changes for readability and unit tests. Great job on the tests :+1:

2021-06-04 00:02 UTC, slaigai commented on languages/python/tests/test_atom.py
> +        for key in keys:
Good work adding this clean-up step at the end of the test. We definitely want to clean up the parameters in case any assertions fail. There might be a way to do that using pytest, or you could go the simple route and add a giant `try ... except ... finally` that cleans up all keys

2021-06-04 00:02 UTC, slaigai commented on languages/python/tests/test_atom.py
> +            assert e._redis_connection_timeout == 2.0
thanks for fixing this type :+1:

2021-06-04 18:38 UTC, sgord512 commented on languages/python/atom/element.py
> +        <<<<<<< HEAD
Fixed in newest commit.

2021-06-04 18:40 UTC, sgord512 commented on languages/python/atom/element.py
> +    def parameter_list(self, pattern="*") -> list[str]:
I changed `pattern` to be `Optional[str]` since that seemed more common in the codebase than default string parameters. I'm not sure if there's a principled reason to prefer one over the other when the default parameter value is immutable. I know there are issues with mutable default parameters.

2021-06-04 18:41 UTC, sgord512 commented on languages/python/tests/test_atom.py
> +    def test_parameter_list(self, caller):
Ok, I've added a comment here.

2021-06-04 20:57 UTC, sgord512 commented on languages/python/tests/test_atom.py
> +        assert len(caller.parameter_list()) == 0
I've split these up, but haven't added comments since I think the assertions are (almost) self-explanatory at this point.

2021-06-04 21:00 UTC, sgord512 commented on languages/python/atom/element.py
> +                        defaults to '*'
I added a separate test that goes into the pattern matching functionality and a link to the redis documentation (which was pretty limited as far as I could tell) which is available here: https://redis.io/commands/KEYS 

I'm not sure how extensively to test the pattern-matching functionality. I've added a few more tests with the basic features documented but I haven't tested escape characters, for example.

2021-06-04 21:00 UTC, sgord512 commented on languages/python/tests/test_atom.py
> +        assert [] == caller.parameter_list("str")
Thanks!

2021-06-04 21:09 UTC, sgord512 commented on languages/python/tests/test_atom.py
> +        for key in keys:
I looked at the tests that involve reading and writing parameters and none of them seemed to do teardown inside a `try...except...finally` block.

What currently happens when an assertion fails is that the assertion failure prevents the cleanup which then results in issues during the teardown for that test. So you only end up with an error in that one test (and then an error in the teardown for that test), but no errors get propagated to other tests. (So this test failing is in fact isolated from other tests failing somehow.) This behavior seems pretty reasonable to me, but I'll defer to you. Should I go ahead and change it to a `try...except...finally` block`?

2021-06-04 21:21 UTC, slaigai commented on languages/python/atom/element.py
> +    def parameter_list(self, pattern="*") -> list[str]:
^ you're absolutely right about the mutable default parameters and @kylebebak knows that this gets me all the time. IMO using `None` to indicate that we want to get all parameters is more explicit as part of the API. In other words, I think `parameter_list(pattern=None)` is more explicit than `parameter_list(pattern="*")`

2021-06-04 21:24 UTC, slaigai commented on languages/python/atom/element.py
> +                        defaults to '*'
Yeah, we don't really need to test that redis matches patterns correctly but we should definitely make sure that the pattern is passed to redis and the results are _generally_ what we expect. With the change you made to the default `pattern=None`, it would be sufficient to parameterize a test with `None`, `exact_match`, and `partial_match_*`

2021-06-04 21:39 UTC, slaigai commented on languages/python/tests/test_atom.py
> +        for key in keys:
Oh nice, that seems reasonable to me as well! As long as we don't leave a dirty redis for other tests then we're good.

2021-06-07 16:45 UTC, slaigai approved these changes
Great work!

2021-06-07 16:55 UTC, dpipemazo requested changes
Looks great! Please add documentation on this to the relevant [docs](https://github.com/elementary-robotics/atom/blob/latest/doc/source/includes/sdk-specification.md)

2021-06-08 16:58 UTC, dpipemazo approved these changes
looks great!

2021-06-08 16:58 UTC, merged