Atom-cli: Fixed the atom-cli records command.
elementary-robotics/atom pull request #477
Opened 2021-06-07 19:25 UTC by sgord512

This commit fixes the atom-cli  records command for the cmdres subcommand and removes the records log subcommand.

2021-06-07 19:36 UTC, dpipemazo requested changes

2021-06-07 19:36 UTC, dpipemazo commented on languages/python/atom/element.py
> +        return f"stream:{element_name}:{stream_name}"
I am not sure this PR should be changing this logic. Please be careful as this can affect others who use this function

2021-06-07 19:56 UTC, sgord512 commented on languages/python/atom/element.py
> +        return f"stream:{element_name}:{stream_name}"
The typechecker already requires element_name to be of type `str`, so I don't think any typed code can trigger this logic. The only caller in the atom codebase I'm aware of that could pass `None` to this function is `atom-cli`, and this change removes the calls to `entry_read_since` that result in the `_make_stream_id` call. (Hence the removal of this codepath.)

After this change, the only callers are in `element.py` which is typed, and `test_atom.py`. `test_atom.py` doesn't call the function with `None`, at least not directly.

Unless I'm unaware of a caller in the untyped part of the codebase, I think this is pretty safe. Do you think I should revert this change?

2021-06-07 20:02 UTC, dpipemazo commented on languages/python/atom/element.py
> +        return f"stream:{element_name}:{stream_name}"
That's a fair analysis; I hadn't considered the typechecker :+1: . 

I'm usually a bit hesitant to make this sort of change as the types were added recently and there may be code in some of our other microservices depending on this. I'm usually a bit hesitant to make small changes like this, but do appreciate that it could simplify the code.

2021-06-07 20:25 UTC, dpipemazo commented on languages/python/atom/element.py
> +        return f"stream:{element_name}:{stream_name}"
Taking a closer look, this is likely a great catch and a change we can make :+1:. After we double-check some of the internal codebases I think we can go ahead and merge this in. Thanks!

2021-06-07 20:27 UTC, dpipemazo approved these changes
:+1: Could you please put a comment up with the new/sample output of the `cmdres` command so that we can review? Otherwise, looking great :+1:

2021-06-07 21:57 UTC, sgord512 commented
Here's an example of the output of `records cmdres atombot`: 
```shell
{
  "element": "atombot",
  "id": "1623031355107-0",
  "language": "Python",
  "type": "response",
  "version": "2.7.1"
}
{
  "element": "atombot",
  "id": "1623031355109-0",
  "language": "Python",
  "type": "command",
  "version": "2.7.1"
}
{
  "cmd": "version",
  "data": "",
  "element": "atombot",
  "id": "1623031355242-0",
  "type": "command"
}
{
  "cmd_id": "1623031355242-0",
  "element": "atombot",
  "id": "1623031355260-0",
  "timeout": "1000",
  "type": "response"
}
{
  "cmd": "version",
  "cmd_id": "1623031355242-0",
  "data": {
    "language": "Python",
    "version": 2.7
  },
  "element": "atombot",
  "err_code": 48,
  "err_str": "",
  "id": "1623031355264-0",
  "type": "response"
}
{
  "cmd": "healthcheck",
  "data": "",
  "element": "atombot",
  "id": "1623031355271-0",
  "type": "command"
}
{
  "cmd_id": "1623031355271-0",
  "element": "atombot",
  "id": "1623031355272-0",
  "timeout": "1000",
  "type": "response"
}
{
  "cmd": "healthcheck",
  "cmd_id": "1623031355271-0",
  "data": "",
  "element": "atombot",
  "err_code": "0",
  "err_str": "Everything is good",
  "id": "1623031355273-0",
  "type": "response"
}
{
  "element": "atombot",
  "id": "1623031383407-0",
  "language": "Python",
  "type": "command",
  "version": "2.7.1"
}
{
  "element": "atombot",
  "id": "1623031383407-0",
  "language": "Python",
  "type": "response",
  "version": "2.7.1"
}
{
  "cmd": "version",
  "data": "",
  "element": "atombot",
  "id": "1623031383460-0",
  "type": "command"
}
{
  "cmd_id": "1623031383460-0",
  "element": "atombot",
  "id": "1623031383475-0",
  "timeout": "1000",
  "type": "response"
}
{
  "cmd": "version",
  "cmd_id": "1623031383460-0",
  "data": {
    "language": "Python",
    "version": 2.7
  },
  "element": "atombot",
  "err_code": 48,
  "err_str": "",
  "id": "1623031383476-0",
  "type": "response"
}
{
  "cmd": "healthcheck",
  "data": "",
  "element": "atombot",
  "id": "1623031383485-0",
  "type": "command"
}
{
  "cmd_id": "1623031383485-0",
  "element": "atombot",
  "id": "1623031383486-0",
  "timeout": "1000",
  "type": "response"
}
{
  "cmd": "healthcheck",
  "cmd_id": "1623031383485-0",
  "data": "",
  "element": "atombot",
  "err_code": "0",
  "err_str": "Everything is good",
  "id": "1623031383487-0",
  "type": "response"
}
{
  "cmd": "version",
  "data": "",
  "element": "atombot",
  "id": "1623031427901-0",
  "type": "command"
}
{
  "cmd": "command_list",
  "data": "",
  "element": "atombot",
  "id": "1623031427910-0",
  "type": "command"
}
{
  "cmd": "version",
  "data": "",
  "element": "atombot",
  "id": "1623082168882-0",
  "type": "command"
}
{
  "cmd": "command_list",
  "data": "",
  "element": "atombot",
  "id": "1623082168916-0",
  "type": "command"
}
{
  "cmd": "move_left",
  "data": "",
  "element": "atombot",
  "id": "1623082177330-0",
  "type": "command"
}
```

2021-06-07 23:47 UTC, kylebebak commented on utilities/atom-cli/atom-cli.py
> +        stream_entries = self.element._rclient.xread(streams)
Much better to have an `xread` call instead of changing the `entry_read_since` API so it can handle this use case. Nice work

2021-06-07 23:58 UTC, kylebebak commented on languages/python/atom/element.py
> +        return f"stream:{element_name}:{stream_name}"
Agreed that it's good to get rid of this and simplify this function as long as we're sure it's not being used by any atom client code. Not only do we simplify it, we don't encourage client code to use it in ways it likely shouldn't be used

UPDATE: just pulled latest for nearly all of our edge repos, then grepped to see where we're using `_make_stream_id`

```
➜  ElementaryRobotics rg _make_stream_id
asset-management/asset_management/download.py
655:            self.element._make_stream_id(

vision-processing/vision/handlers/stream.py
118:        stream_name = element._make_stream_id(

atom/languages/python/atom/element.py
516:        self._rclient.unlink(self._make_stream_id(self.name, stream))
636:    def _make_stream_id(self, element_name: str, stream_name: str) -> str:
911:        return self._redis_scan_keys(self._make_stream_id(element_name, "*"))
1972:            stream_id = self._make_stream_id(
2073:            stream_id = self._make_stream_id(element_name, stream_name)
2192:            stream_id = self._make_stream_id(element_name, stream_name)
2323:                self._make_stream_id(self.name, stream_name), vars(entry), maxlen=maxlen
2904:            stream_name = self._make_stream_id(element, stream)

atom/languages/python/tests/test_atom.py
46:            private_sn = element._make_stream_id(element.name, s)
199:        assert caller._make_stream_id("abc", "123") == "stream:abc:123"
```

It's used nowhere but atom, and it hasn't broken anything in atom, so this looks great =)

2021-06-08 00:01 UTC, kylebebak approved these changes

2021-06-08 20:19 UTC, merged