remove print statements for loop start and end
elementary-robotics/atom pull request #529
Opened 2022-02-18 05:16 UTC by avdm12-elementary

## Change description

> Description here

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-02-18 17:25 UTC, aywaldron requested changes
Hey @avdm12-elementary , I just realized there is actually an atom `element` created in the main loop of this function which we could use for logging instead of print statements. Might be good to change these to log through the atom element at debug level, e.g. `element.log(LogLevel.DEBUG, ...)`.

2022-02-18 17:26 UTC, aywaldron commented on metrics/monitoring/metrics_monitor.py
>      # Loop forever
We can change the print statement at line 624 to be logged via atom as well, at INFO level

2022-03-01 18:56 UTC, aywaldron approved these changes
LGTM, thanks for getting this up!

2022-03-04 22:48 UTC, dpipemazo approved these changes
Thank you!

2022-03-05 00:02 UTC, merged