Adding API functionality for shared memory
elementary-robotics/atom pull request #541
Opened 2022-04-05 00:25 UTC by ashule01

...reference_create, reference_get, and reference_delete for shared memory

## Change description

> Adding functionality for creating, getting, and deleting shared memory references through the current reference API. These changes are backwards compatible by creating redis references if no ref_type is specified

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-04-06 17:51 UTC, iourielementary approved these changes

2022-04-06 18:16 UTC, jgauth commented on languages/python/atom/element.py
> +            # _pipe = self._rpipeline_pool.get()
delete?

2022-04-06 18:16 UTC, jgauth commented on languages/python/atom/element.py
> +            name = ATOM_SH_MEM_NAME
It seems like this could be replaced with setting the name argument to default to `ATOM_SH_MEM_NAME` instead of `None`

2022-04-06 18:16 UTC, jgauth commented on languages/python/atom/element.py
> +            self.metrics_timing_end(
nothing happens between timing start and end?

2022-04-06 18:49 UTC, aywaldron requested changes
Overall functionality looks great; suggestions are mainly around error handling, documentation, testing and style. Please make sure we have types defined in all function parameters.

One code change that I think could be helpful is to have classes for the different reference types, that define their unique reference create/get/delete functions. We do something like this with the serialization options [here](https://github.com/elementary-robotics/atom/blob/latest/languages/python/atom/serialization.py#L15). For example:
```
class AtomReference:
    @classmethod
    def reference_create(cls, data):
        raise(NotImplementedError)

    @classmethod
    def reference_get(cls, key):
        raise(NotImplementedError)
        
    @classmethod
    def reference_delete(cls, key):
             raise(NotImplementedError)

class RedisReference(AtomReference):
     # override the above methods with the methods you've defined on Element
     
class SharedMemReference(AtomReference):
     # override the above methods with the methods you've defined on Element
```

2022-04-06 19:01 UTC, dpipemazo requested changes

2022-04-06 19:01 UTC, slaigai commented on languages/python/atom/element.py
> +                        raise ValueError(f"Invalid response from shared_mem: {data}")
NIT: Error string should indicate that data must be `np.ndarray` when using shared mem. Though the string is accurate, it does not explain _why_ the response is invalid so that the reader can understand/fix the issue.

2022-04-06 19:07 UTC, slaigai commented on languages/python/atom/element.py
> +                success = success and redis_success
:+1:

2022-04-06 19:17 UTC, ashule01 commented on languages/python/atom/element.py
> +            name = ATOM_SH_MEM_NAME
Good call out!

2022-04-06 19:50 UTC, aywaldron commented on languages/python/atom/element.py
> +        """Cleans up all tags associated with this element"""
I think we should take Dan's suggestion below and have tags scoped to the element that creates them so we don't have multiple elements using the same tag. If we do this, we should also add the element name to the tag name the user specifies before passing it onto the shared mem library, e.g. if the basler element wants to create a reference under the `image` tag, we construct the tag `basler:image` to pass to the shared mem lib.

2022-04-06 19:51 UTC, aywaldron commented on languages/python/atom/element.py
> +        tag = tag if tag else self.name
I think this is a good idea and allows us to cleanup tags on element cleanup.

2022-04-06 19:53 UTC, aywaldron commented on languages/python/atom/element.py
> +                        tag_name, tag_max_len, datum, datum.size
Great catch -- is there another more generic way to get data size we could use here than calling `.size`? Our first use case for this API is numpy arrays but I'm not sure we want/need to make it specific to that data type.

2022-04-06 21:27 UTC, ashule01 commented on languages/python/atom/element.py
> +            return_data = self._reference_get_redis(
The idea would be that you can retrieve multiple keys regardless of their type in a single call. Because return data is passed in to both redis and shared_mem reference_get functionality and the return data is stored in the exact same order that the keys are passed in (via the index of the key in the original keys array), you wouldn't end up overwriting it. I ended up implementing it this way because I wanted to avoid having to copy data over from different return data lists from the different reference types to be able to return a single value

2022-04-06 22:05 UTC, ashule01 commented on languages/python/atom/element.py
> +            return AtomRefType(ref_type_val)
So you need (...) here instead because ref_type_val is the value assigned to the enumeration (ex: "shared_mem") instead of the name of the enum (ex: SHARED_MEM), so by accessing it via parentheses, you are getting the name of that AtomRefType for the given val

2022-04-06 22:31 UTC, ashule01 commented on languages/python/atom/element.py
> +                return_data_index = int(keys[key])
Good call out on this -- so in order to avoid getting the data from shared_mem and redis keys separately then having to recombine the data into a single list to return from reference_get, keys in this function is a dictionary made up of the keys and their indices in the original keys array (ex: {"key":index_of_key_in_original_keys_array}) which allows us to return the data in the proper order without having to copy to a new array when reordering it. The naming is unclear though and not having typehints definitely makes this confusing as well. I'll add both

2022-04-06 22:35 UTC, ashule01 commented on languages/python/atom/element.py
> +        shared_mem_keys, redis_keys = self._split_keys_by_ref_type(*keys)
So we could combine for sure but the small hiccup is that for redis keys, the key is "gotten" but not until we run _pipe.execute() does it actually get all the data. So the pipeline for getting then properly formatting the data between shared_mem and redis are slightly different

- shared_mem: get data for each key individually and add it to the return data as we get it
- redis: get the data for all keys at the same time then properly format/deserialize it by looping through again then adding it to the return data

So to answer, we could but it does make combining the two kind of awkward since we don't want to fetch the redis results until we've added them all to the get queue via _pipe.get(key)

2022-04-06 22:44 UTC, slaigai commented on languages/python/atom/element.py
> +            return AtomRefType(ref_type_val)
Ohhhhhh you're right. I learned something today :)

2022-04-06 22:47 UTC, slaigai commented on languages/python/atom/element.py
> +            return_data = self._reference_get_redis(
Oh gotcha, so the `return_data` going into the function is the same object reference that gets returned. Makes sense now that you point it out! I didn't read carefully enough to pick that up

2022-04-06 22:48 UTC, aywaldron commented on languages/python/atom/element.py
> +                        raise ValueError(f"Invalid response from shared_mem: {data}")
@ashule01 Is the shared mem lib doing a check for `np.ndarray` type? Or does it allow other data types as well? I can't remember what we landed on there.

2022-04-06 22:48 UTC, ashule01 commented on languages/python/atom/element.py
> +                        tag_name, tag_max_len, datum, datum.size
So this is specified in the shared_mem library that it has to be an numpy array made up of ints -- definitely means I should add some more data type checking earlier in the process, but we are currently restricted to only numpy arrays of ints for shared memory

2022-04-06 22:49 UTC, aywaldron commented on languages/python/atom/element.py
> +                        tag_name, tag_max_len, datum, datum.size
Ah I see, thanks for clarifying. Can disregard by other comment asking the same question :)

2022-04-06 22:52 UTC, aywaldron commented on languages/python/atom/element.py
> +        shared_mem_keys, redis_keys = self._split_keys_by_ref_type(*keys)
Ok, that makes sense. Let's stick with your current implementation then but maybe try to make the return data usage a bit more clear to a reader since it seems there's some confusion over how exactly its working.

2022-04-06 22:57 UTC, aywaldron commented on languages/python/atom/element.py
> +                return_data_index = int(keys[key])
Yeah, including more information in the docstring may also help since right now it suggests `keys` is just a list of keys.

2022-04-08 00:53 UTC, ashule01 commented on languages/python/atom/element.py
> +            return_data = self._reference_get_redis(
I'll definitely add a comment describing this though because it is definitely not obvious how this is working! Thanks for the comment on this :)

2022-04-08 19:22 UTC, dpipemazo commented on languages/python/atom/element.py
> +                        data = atomshmem.atom_shmem_get(handle)
```
data, w, h, d = atom_shmem_get(...)
data.dtype = numpy.uint8
data.shape = (w, h, d)
data.strides = (h*3, h, 1)
```

2022-04-08 19:25 UTC, dpipemazo commented on languages/python/atom/element.py
> +                        tag_name, tag_max_len, datum, datum.size
```
alloc_id = atomshmem.atom_shmem_alloc_init(
    tag_name, tag_max_len, datum, datum.size, w, h, d)
```

where:
```
w, h, d = np.shape()
```

2022-04-14 22:06 UTC, ashule01 commented on languages/python/atom/element.py
> +        tag = tag if tag else self.name
I implemented this by setting it up as {element name}-{additional tag} with additional tag defaulting to "default" so you'd get something like `basler-default` if no additional tag is passed.

2022-04-15 00:36 UTC, aywaldron requested changes
Looks great Allison, thanks for making all the changes! Couple minor suggestions and questions left, overall looks very solid and test coverage looks very good :tada:

2022-04-15 00:36 UTC, aywaldron commented on languages/python/atom/element.py
> +            ref_key += f":ser:{serialization}"
If we are using serialization of "none" (I believe the default for most of the API) does it still get included here? We would want it to.

2022-04-15 00:36 UTC, aywaldron commented on languages/python/atom/element.py
> +
My understanding was we wanted to do `reference:{self.name}:{tag}:{key}` for shared mem references; I don't think this allows that?

2022-04-15 00:36 UTC, aywaldron commented on languages/python/atom/element.py
> +                    failed_allocs.append(e)
:+1:

2022-04-15 00:36 UTC, aywaldron commented on languages/python/atom/element.py
> +                tag_name += tag if tag is not None else "default"
Oh I see the element name is being added here. Makes sense!

2022-04-15 00:36 UTC, aywaldron commented on languages/python/atom/element.py
> +                    )
Perhaps this should be a DEBUG log instead of a print statement?

2022-04-15 00:36 UTC, aywaldron commented on languages/python/atom/element.py
> +                        shape[i] = val
:+1:

2022-04-15 00:36 UTC, aywaldron commented on languages/python/atom/element.py
> +        )
:+1:

2022-04-15 00:36 UTC, aywaldron commented on languages/python/atom/element.py
> +                unidentified_keys[key] = i
We should probably never hit this because we assume redis type if "type" isn't in the key, right?

2022-04-15 00:36 UTC, aywaldron commented on languages/python/tests/test_atom.py
> +        assert ret == True
Should we test that we can't add a piece of data to it now that its deleted?

2022-04-15 00:36 UTC, aywaldron commented on utilities/scripts/clear_shared_mem.py
> +            print(f"Error in getting shared mem pointer: {str(e)}")
Should we indicate that we can't delete it here? To make it clear that shared memory was not wiped on startup.

2022-04-15 00:36 UTC, aywaldron commented on utilities/scripts/clear_shared_mem.py
> +            return
Let's print that we were successful in clearing it out

2022-04-15 00:37 UTC, aywaldron commented on languages/python/atom/element.py
> +
NVM this comment, I saw how its working below.

2022-04-15 00:54 UTC, ashule01 commented on languages/python/atom/element.py
> +
Yeah definitely open to talking about the "-" vs ":" syntax because colon would definitely cleaner but would make the parsing a little clunkier since we want to include the name and the tag in the shared memory tag -- open to doing it either way

2022-04-15 00:55 UTC, ashule01 commented on languages/python/atom/element.py
> +                    )
oh shoot apologies, that was from testing  -- I'll clean it up and make it debug

2022-04-15 22:18 UTC, ashule01 commented on Dockerfile
> +ADD ./utilities/scripts/clear_shared_mem.py /usr/local/bin/clear_shared_mem.py
Good call, and yeah it doesn't need any further requirements

2022-04-15 22:22 UTC, ashule01 commented on languages/python/atom/element.py
> +            ref_key += f":ser:{serialization}"
"ser:none" will be included for any reference created in reference_create:
For redis, serialization gets specified here: https://github.com/elementary-robotics/atom/blob/281b8403c698aa18d4330b7de2651ced8fd6eb4a/languages/python/atom/element.py#L2929
And for shared mem, serialization is always none: https://github.com/elementary-robotics/atom/blob/281b8403c698aa18d4330b7de2651ced8fd6eb4a/languages/python/atom/element.py#L3050

But in reference_create_from_stream, the serialization was not previously specified in the key: https://github.com/elementary-robotics/atom/blob/281b8403c698aa18d4330b7de2651ced8fd6eb4a/languages/python/atom/element.py#L3236

2022-04-15 23:16 UTC, aywaldron commented on languages/python/atom/element.py
> +            ref_key += f":ser:{serialization}"
Ok that all sounds fine, thanks for checking!

2022-04-15 23:17 UTC, aywaldron commented on languages/python/atom/element.py
> +
I think what you have is good! so it'll look like `reference:camera-image:1234`

2022-04-15 23:18 UTC, ashule01 commented on languages/python/atom/element.py
> +
Yup!

2022-04-20 19:54 UTC, aywaldron commented on languages/python/tests/test_atom.py
Does this test destroy the shared memory for all subsequent tests? Might want to explicitly document that if so.

2022-04-20 19:55 UTC, aywaldron approved these changes
Looks great Allison, thanks for working through all the feedback. One suggestion on documentation in the unit tests, otherwise approving.

2022-04-20 19:58 UTC, aywaldron requested changes
Actually one more request to update the atom docs in [here](https://github.com/elementary-robotics/atom/tree/latest/doc/source/includes) with the API changes.

2022-04-21 01:41 UTC, ashule01 commented on languages/python/tests/test_atom.py
Updated the test accordingly because the shared memory attempts to get created at the start of every test because of the creation of the "test" element. Thanks for the call out here

2022-04-22 02:47 UTC, dpipemazo approved these changes
My comments are mainly nits -- looks great! Excited to try this out.

2022-04-22 15:23 UTC, aywaldron approved these changes
Thanks for the docs!

2022-04-25 17:00 UTC, slaigai approved these changes

2022-04-25 17:02 UTC, merged