New monitoring metrics
elementary-robotics/atom pull request #547
Opened 2022-04-27 20:37 UTC by sammsaski

## Change description

> Adding total cpu metric capturing as opposed to per core, started recording system load average.

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-04-28 18:34 UTC, aywaldron requested changes
Looks good Sam, just a couple small suggestions.

As for the failing builds, it looks like this is the redis key cleanup issue we've been tracking already. Try rerunning them to see if you can get them to pass. If not, we may have to experiment with adding a sleep somewhere in the tests to see if we can resolve this issue.

2022-04-28 19:45 UTC, ashule01 commented on metrics/monitoring/metrics_monitor.py
> +    cpu_freq = psutil.cpu_freq().current * 1000000
NIT: similar comment to Anna's above about 10e6

2022-04-28 19:55 UTC, sammsaski commented on metrics/monitoring/metrics_monitor.py
> +    cpu_system_load_avg = [
Yep, it's saving the average over the last minute upon calling. This isn't configurable when using `psutil` unfortunately. The title for the actual graph is marked with `(1 min)` to denote this, but it still needs to be updated in the performance stoplight section of the graph.

2022-04-28 22:26 UTC, aywaldron commented on metrics/monitoring/metrics_monitor.py
> +    cpu_percent = psutil.cpu_percent()
Could you add comments clarifying this one is overall and the previous one with `percpu=True` is per core? documenting as much as possible will help out in the future. Same for the `cpu_freq` calls below

2022-04-29 00:17 UTC, aywaldron commented on metrics/monitoring/metrics_monitor.py
> +        load_avg / psutil.cpu_count() * 100 for load_avg in psutil.getloadavg()
Is the 100 here to make it a percentage? Would be helpful to document that in a comment as well.

2022-04-29 16:21 UTC, dpipemazo approved these changes
Thanks @sammsaski ! :tada:

2022-04-29 18:04 UTC, merged