Ers1249/ref counters
elementary-robotics/atom pull request #550
Opened 2022-05-04 23:37 UTC by ashule01

## Change description

> Adding reference counters for number of shared memory and redis references (not taking auto-pruning into account) and size of shared memory. Updated tests to check these counters and to clean any lingering counters. Also fixed typo for env var

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> https://elementary.atlassian.net/browse/ERS-1249

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-05-05 17:31 UTC, aywaldron requested changes
Looks really good Allison, couple small ish comments. I see that we're not initializing the counters anywhere, maybe that's not required though?

2022-05-05 17:31 UTC, aywaldron commented on languages/python/atom/element.py
> +
Would it be safer to take the len of `ref_ids` here in case a ref create failed on one of the data?

2022-05-05 17:31 UTC, aywaldron commented on languages/python/atom/element.py
> +                total_data_size += datum.size
I think this give us the number of elements in the array, not the total size in memory.

2022-05-05 17:31 UTC, aywaldron commented on languages/python/atom/element.py
> +        self.counter_update(AtomRefCounters.NUM_SHARED_MEM.value, len(data))
Same question here as above, I think taking the length of `ref_ids` is more accurate.

2022-05-05 17:31 UTC, aywaldron commented on languages/python/atom/element.py
> +                        for dim in get_return_data[2:5]:
To make this more readable could we do something like
```
data, shape, width, height, depth = atomshmem.atom_shmem_get(handle)

for dim in (width, height, depth):
    ...
```

2022-05-05 17:31 UTC, aywaldron commented on languages/python/atom/element.py
> +        self.counter_update(AtomRefCounters.NUM_REDIS.value, len(failed) - len(keys))
The idea is that `len(failed) - len(keys)`  gives us a negative number, right?

2022-05-05 17:31 UTC, aywaldron commented on languages/python/tests/test_atom.py
> +
This test looks really great :tada: 
Would it be worth testing that a second element interacts smoothly with the same counters?

2022-05-05 18:00 UTC, ashule01 commented on languages/python/atom/element.py
> +        self.counter_update(AtomRefCounters.NUM_REDIS.value, len(failed) - len(keys))
Yup! I'll add a comment to make that more explicit

2022-05-05 18:00 UTC, ashule01 commented on languages/python/tests/test_atom.py
> +
Oh yeah good call on that

2022-05-05 18:01 UTC, ashule01 commented on languages/python/atom/element.py
> +                total_data_size += datum.size
Because each value in the  array is a uint8, this gives us the number of bytes

2022-05-05 18:21 UTC, ashule01 commented on languages/python/atom/element.py
> +
In this case, it doesn't really matter because an exception gets thrown if there is an issue with any of the creates. len(ref_ids) is equivalent to len(data) because ref_ids are set even before the create is executed. I agree though that it is cleaner, so I'll update

2022-05-05 18:26 UTC, ashule01 commented on languages/python/atom/element.py
> +
Actually, this counter should be moved above the Error that is thrown and should be incremented based on the number of responses that were successful so the counter reflects the case where some successfully insert even when an Error gets thrown

2022-05-05 18:30 UTC, aywaldron commented on languages/python/atom/element.py
> +                total_data_size += datum.size
Ah ok perfect. Could we add a comment clarifying that?

2022-05-05 18:37 UTC, aywaldron commented
> That does mean that these counters could linger across inspections though

I think this is what we want as long as it correctly reflects the references that still exist -- we'll need to make sure that when we have elements cleaning up tags on start up, we decrement the counters appropriately. Not in the scope of this PR but it might require shared mem API updates.

2022-05-09 19:42 UTC, aywaldron approved these changes
Functionality all looks good to me :+1: couple small questions/suggestions on comments. Thanks for working through the API changes!

2022-05-09 19:42 UTC, aywaldron commented on languages/python/tests/test_atom.py
> +            responder.counter_delete(ref_counter.value)
Do we clean these up here just to get a clean slate for testing?

2022-05-09 19:42 UTC, aywaldron commented on languages/python/tests/test_atom.py
> +        ref_data = caller.reference_get(*ref_id)[0]
Just curious is it necessary to call with `*ref_ids` or is it possible to pass in just `ref_ids` without the star?

2022-05-09 19:48 UTC, aywaldron commented on languages/python/tests/test_atom.py
> +        assert np.array_equal(ref_ids, [None])
We could also check here that the counter hasn't incremented.

2022-05-09 20:06 UTC, ashule01 commented on languages/python/tests/test_atom.py
> +            responder.counter_delete(ref_counter.value)
Yeah because any test that makes a reference will create this counter so if we don't clean them up the lingering ones throw an assertion error in check_end_redis

2022-05-09 20:09 UTC, ashule01 commented on languages/python/tests/test_atom.py
> +        ref_data = caller.reference_get(*ref_id)[0]
so you can call it with ref_id only if it is a single ref id as a string or you can call it with *ref_ids where ref_ids is a list. The change here is because we used to do reference_create()[0] which would make it so ref_id was a string, but since we are now returning a tuple (bool, list of ids) we can't use the [0] on the same line to get the first value anymore. This code would work in one of two ways:
```
success, ref_id = caller.reference_create(data) #ref_id here is a list
ref_data = caller.reference_get(*ref_id)[0]
```

```
success, ref_ids = caller.reference_create(data) #ref_ids here is a list
ref_id = ref_ids
ref_data = caller.reference_get(ref_id)[0]
```

2022-05-09 21:01 UTC, aywaldron commented on languages/python/tests/test_atom.py
> +        ref_data = caller.reference_get(*ref_id)[0]
Ok thanks for explaining!

2022-05-09 21:03 UTC, aywaldron commented on languages/python/atom/element.py
> +                # ref_ids.append(None)
Can probably delete this

2022-05-09 22:33 UTC, dpipemazo approved these changes
Looks great -- just some minor nits/questions!

2022-05-09 22:33 UTC, dpipemazo commented on languages/python/atom/element.py
> +                            if dim != 0:
this is an interesting edge/corner case. Do we have unit tests covering how we handle arrays with zero-size dimensions? Might be good to add it in if not, since this seems like it can subtly break.

2022-05-09 22:52 UTC, ashule01 commented on languages/python/atom/element.py
> +                            if dim != 0:
Do you mean where one or more of the dimensions is 0 because we have the following for 1, 2, 3, and 4D data (in case of the 4D we get a failure):
1D: https://github.com/elementary-robotics/atom/blob/3d08c1cbb2a115ea3fd8178de18ba536fedd4ebb/languages/python/tests/test_atom.py#L1443
2D: https://github.com/elementary-robotics/atom/blob/3d08c1cbb2a115ea3fd8178de18ba536fedd4ebb/languages/python/tests/test_atom.py#L1489
3D: https://github.com/elementary-robotics/atom/blob/3d08c1cbb2a115ea3fd8178de18ba536fedd4ebb/languages/python/tests/test_atom.py#L1499
4D: https://github.com/elementary-robotics/atom/blob/3d08c1cbb2a115ea3fd8178de18ba536fedd4ebb/languages/python/tests/test_atom.py#L1509

2022-05-09 22:53 UTC, dpipemazo commented on languages/python/atom/element.py
> +                            if dim != 0:
Nice! I had no particular thoughts in mind; just thought it was the kind of clause in code we should ensure we test around the corners of. If you're confident we have the tests we're in good shape. Thanks!

2022-05-10 16:18 UTC, merged