Ers2794/tag cleanup
elementary-robotics/atom pull request #557
Opened 2022-05-23 18:45 UTC by ashule01

## Change description

> Add tag cleanup functionality on element init and cleanup. Tags are optionally passed in on element init which enables the element to cleanup tags on init and clean_up. Additionally added function to get amount of free shared memory.

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> https://elementary.atlassian.net/browse/ERS-2794

## Checklists

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2022-05-23 18:49 UTC, iourielementary approved these changes

2022-05-23 21:00 UTC, aywaldron requested changes
Overall looks good, some comments/questions on the tests

2022-05-23 21:08 UTC, ashule01 commented on languages/python/atom/element.py
> +                success = True
It could get a little spammy on startup, depending on how many tags we are dealing with, but we could always log here and then remove if it is annoying

2022-05-23 21:09 UTC, ashule01 commented on languages/python/tests/test_atom.py
> +        test_element._clean_up()
It tests that  init and cleanup of a non-existent both succeed

2022-05-23 21:12 UTC, aywaldron commented on languages/python/atom/element.py
> +                success = True
ok yeah I'm fine either way

2022-05-24 00:19 UTC, ashule01 commented on languages/python/atom/element.py
> +                total_num_handles_removed += num_handles_removed
The only reason we would be getting a False would be if there was an AtomSharedMem error which returns a negative value representing the error code, not any number of handles -- if something goes wrong and some handles are removed and others aren't, we wouldn't know

2022-05-24 00:25 UTC, ashule01 commented on languages/python/atom/element.py
> +                total_num_handles_removed += num_handles_removed
I do think it is a good idea to move it into `_shared_mem_cleanup_tag` in case we do a cleanup that isn't through `_cleanup_shared_mem_init_tags`. It will mean some duplicate calls to depreciate the ref counter, but that should be negligible

2022-05-24 00:41 UTC, ashule01 commented on languages/python/tests/test_atom.py
> +        test_element._clean_up()
The only way to do this is to try and clean them up again and get a `success, 0` return value, so I can add that at the end :+1:

2022-05-24 00:59 UTC, aywaldron commented on languages/python/tests/test_atom.py
> +        test_element._clean_up()
Ah ok, a comment explaining that would be helpful!

2022-05-24 16:59 UTC, aywaldron approved these changes
Changes looks great, much cleaner. Couple minor questions, but approved from my end.

2022-05-24 16:59 UTC, aywaldron commented on languages/python/atom/element.py
> +        if self._use_shared_mem and self._shared_mem_clear_tags is not None:
Thanks for the comment :+1:

2022-05-24 16:59 UTC, aywaldron commented on languages/python/atom/element.py
> +        """
Could add to the docstring that this method will raise an exception if there's any issue accessing shared mem.
Should we check `self._use_shared_mem` before calling the `atomshmem` function?

2022-05-24 16:59 UTC, aywaldron commented on languages/python/atom/element.py
> +        return num_handles_removed
Nice, this is a lot cleaner :+1:

2022-05-24 16:59 UTC, aywaldron commented on languages/python/atom/element.py
> +                raise (e)
:+1:

2022-05-24 16:59 UTC, aywaldron commented on languages/python/tests/test_atom.py
> +        assert num_handles_removed == 0
Is this check redundant to lines 2156-2157?

2022-05-24 20:32 UTC, merged